language: node_js
node_js:
- '8'
addons:
  chrome: stable
install:
- wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/
- sudo chmod +x /usr/local/share/chromedriver
- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
services:
- mysql
script:
- sh scripts/ci_script.sh
- whereis google-chrome-stable
- whereis chromedriver
before_install: gem install sass
env:
- MYCRT_ENV=travis
notifications:
  slack:
    secure: j+UuDmxi6kpFN5cF6JJ/JKIIstZ+ZEfDqQtwBLuPUKwjYpw3ezCRRZyN742wZYykySLZJCJE7b92x4nFzAKNYHxY10g8I0VgfRsJVmlu94zI/+1+Fl63XAqNyJmP1rOVqRSRRYI8tbZsO0HZ5zZjpL8Av+NTFB2+8cMQXp746Ak0tRLwqe0YaXTI+XijEGLq8qnyNXCJX2F6gAx1ceLiAgTq3N2+sCEoLukrtLs8JsVHpLWTsSSkUZTeWelLIaUOGV6Y/OUUFhfJMIN5ScS7t8/vG4jouh+OXpzmHsQnek59qZ6rVPc129a52wdwqUlFrEL5j0M53gEzecw8TjYyCAxGaMpZJiF6IlwOCvgVyUtGYvopZSz7751JRpidsXa6bwITLKJtnBYFb4iJqUtU/QjkZWTtndbyMXYybndpO54rqlPaI3S0iHd7R2YeY5MdO7n8x37VOPDheXdd4BOv3OPvkIynFLXwyHU4twgu1zBenFfkWT8l112CLM6K0jU59PZkDC6v6HaCpF76yRGbwhgIewNIElJoxGDR4S1ocQj6KCSUeBY8VKBy3X8iA7ZJmF92N5OCLpmo4TTQ7HXfHqdZLYctFsTAnSutLj3eYqW5pidThzKVdz3jEfGzWKcsIr1WxaqKDrzqoj+al6SlSyjmkI3BIkeXP7xHnZYH0/k=
