language: node_js
node_js:
   - "8"
cache:
   - "node_modules"

script: sh scripts/ci_script.sh

notifications:
  email:
    recipients:
      - axis7818@gmail.com
      - cdushana@gmail.com
      - hilaryschulz@gmail.com
      - nishanth.dara@gmail.com
      - primenewby@gmail.com
      - alexdeany@gmail.com

    on_success: never
    on_failure: always
