language: node_js
node_js:
- '8'
script: sh scripts/ci_script.sh
before_install: gem install sass
notifications:
  slack:
    secure: ZiRy8Xbtip5jrJUMFUIz+FDj90zSun8Q9gLdlamlpR2Z+O05RuFTcoTOFn4BUfxpkmv5sDtuVIZXGe89W+Rth0cdfv/mfHYWdD2+Arr5LHRUW9mnVczdky8zqSeB08wMXdccIPG3GGmgHJEmNV0FHn/DVnXj0MkAb0fJDUzWG6fY8ZGdmsFoEDesJ3EmKLy3mQ2X7I01e50ougvmoFVobA1kjm+IJI01dTIj4ifFxSBEQ1NqB2f9n+GN7+cSSZi8UDnLfiRyRS6n2+w/e5d56Abn/mN/lwwZr2vASxLvAWxxmApYrjW9P9bB1jw+7cjUjLP0U68WMXhNf90uE9OYDV4F5VTNgxT6gHubMJP36bQh9u6X5tm0IjDNmzrfb9g8QM6zJDuQLuGV/XdZTVhknDwfixrsdNojs762EQ4XarIAGjWoqWup+iIazNfZAH7QQntj+fJPCzhUnqkiBmGKVi6bk5FvyawjwNmqjRDsdKJvPRHR67jh6f3fQBm2XdVW16pzapEoqyoh4+HYHf7H+8qG5GCDuvNSg1nfXl/e3Hvaf1fsZ/xsorwapHA/N5sWjqhcLSEYwj4+W8K8ECdMRmgv5RygvZYlvjCS7X4/Z5UAiU82IIFHdbIRxPC3FIMvLucNiFImUXRUOlD4i11mjbULaarsg7hnEythEl89B2Y=
