language: node_js
node_js:
   - "8"

script: sh scripts/ci_script.sh
before_install: gem install sass

notifications:
  slack:
    secure: k9aBHHHo/8fx9Ko7rdWZMKwctMV4m501+D/KJn5iavQ9wNUKNZtAy3lUuBACg3e5mSSlyiYTiZyrU8ntL8bGl5q9AukyP6fX7hHLqjCY5A95Iebmh3nVMDDhKje8zgYqj9B9UBx2Lx4a4a5LQh4gelwuAphvV3szj/HMUwywCslwd/r+xAkuxxCecNbqjqnA5d6Xag6ntNWJcCaQGZ5aXkhcAhYWd7d7MfPoriFxeR1WLN1g7vRUgcBg3EWXGyIuVVD6JgVHTxh+26ePONJvJPv8ZD53uZ0TSc7/8wNoSNqldU1paXLVkN3myxVVQUD6RWE98b8KMcnhywUUvfACkWYv0xOuOw+HD2DkFmoAXmkD06t28gR6JqbaxfAGSteLyjA9+ZDbp3HiwEs9yJ9KobLfoJYUY8PG/J/QwpWyalRl9HIhXLycnJcEsUL/f8my+JwO0Wp5MAX+7/FYJkSKU8IrSiBcaHtb4taRPkOd0r+5r6A863jAypjF0nw0KPUfZI7WRitYyRVm/B1RMs3PUTeD3E73/0jWIBtEeeTlZjyAo73KVrCu67q/YZRQN7SEIt5diFPezemkTu9mmHK6ACpMRFoP407VYSG+qrCyKUNzzzNv8//tlQrJG0P9bKRH97hVxcugn/XDT/5zIkayT6f2z7PUy3KhUOo4zD3kSi0=
