language: node_js
node_js:
- '8'
script: sh scripts/ci_script.sh
before_install: gem install sass
notifications:
  slack:
    secure: 7AqRHfQrEyEAu8EWooTZZf7GiZ/dTlUwxF120s8fp+RVW5MGoML2XNH+Irqz5fh/tHlzBKzcoxmrRbrYqMzbmNSoetaEJZCx1FSRGUiSIlxv7CLASGJX/Xncuzy/8xn/5RpOIw+WbjTezFh1UEa9EJyBFIPlFohT/fxhPwLwF8ojyrnGnOUaqZ7xDQUDehSgziKt60xWyNclkKcCAuUlLCPGZWZNDqXuxq+XNdB6y+qLnTVxVGcBcEmj3/z5eJBizBGl1nSuXh1gcMYUHWlJJJh+Xr5c9xFyL+eZlz6d2bijHcsRStWftGobFhbVNQID1AIDDsIrcWoAb1L8WOgrfKUNYelbRG6hmX7qeSKv5bnTK187Cz7J1h/ETcbTE3rO3jCNUP8t4RWb+gjjJxs6T3r9gejqhe2el9B0V4+sZESA0Obk6oK4vOqCwKlPITJwTlrfav9K9vU4MOpoh0l2nMC+TLO9pT4IaMficRm5vMCTSvIwisDzSyfg51y8OORPj+jFEAnHBYIRkd45rjReC9t+X4P5ADShGUevUAE8BdJK5W5dr1N5HShIfdzzDVJ0a6zO0AAQbmsq2thN/48hL2Isx7VaadERFv5AkrBOf13GnOL6jJBl8467Pasy2K3bbpiFfr5ItzPD7dN72ntqJZaGLob0Zskj19HJekCfEzs=
