DROP DATABASE IF EXISTS LBTMyCRT;
CREATE DATABASE LBTMyCRT;
USE LBTMyCRT;

CREATE TABLE Environment (
   id int(11) AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(32),
   dbId INT(11) REFERENCES DBReference(id),
   s3id INT(11) REFERENCES S3Reference(id)
);

CREATE TABLE DBReference (
   id int(11) AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE S3Reference (
   id int(11) AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE Metrics (
   id int(11) AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE Capture (
   id int(11) AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(32),
   start DATETIME,
   end DATETIME,
   envId INT(11) REFERENCES Environment(id)
);

CREATE TABLE Replay (
   id int(11) AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(32),
   start DATETIME,
   end DATETIME,
   capId INT(11) REFERENCES Capture(id)
);